name: Push to GHCR

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # every week

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v2

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: container-minecraft-server
          tags: latest ${{ github.sha }}
          archs: amd64, arm64
          containerfiles: |
            ./Containerfile
          oci: true

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
